# Generated by Django 5.1.1 on 2024-10-05 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_crated_at_certificate_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="period",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 5, 10, 4, 43, 555283)
            ),
        ),
    ]
