# Generated by Django 5.1.1 on 2024-10-05 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="period",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 5, 10, 6, 20, 146452)
            ),
        ),
    ]
