# Generated by Django 5.1.1 on 2024-10-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="period",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
