# Generated by Django 5.1.1 on 2024-10-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_creditcard_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingaddress",
            name="credit_cards",
        ),
    ]
