# Generated by Django 5.1.1 on 2024-10-01 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_billingaddress_options_billingaddress_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingaddress",
            options={
                "ordering": ["id"],
                "verbose_name": "Billing Address",
                "verbose_name_plural": "Billing Addresses",
            },
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
