# Generated by Django 5.1.1 on 2024-10-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_invoice_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='user',
            new_name='account',
        ),
    ]
