# Generated by Django 5.1.1 on 2024-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="crated_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                default="0d64989794b1a4c9d89bff571d3d5842.jpg", upload_to="avatars/"
            ),
        ),
    ]
